apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-demo2
  title: Backstage Demo2
  description: Aplicação teste2
  namespace: stone
spec:
  type: website
  lifecycle: experimental
  owner: pagarme/sre-platform
  system: system:pagarme/backstage
