apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-portal
  namespace: first-error
  title: Backstage Portal
  description: The StoneCo developer portal
  annotations:
    stone.tech/cloud-accounts: aws/pagarme-tools
    legacy.stone.tech/prod-date: "2023-03-01"
    legacy.stone.tech/owner-email: dmorales@stone.com.br
  labels:
    stone.tech/endpoint-type: private
    legacy.stone.tech/internal-user-auth-base: sso
    legacy.stone.tech/access-request-type: github
    legacy.stone.tech/handle-lgpd: "false"
    legacy.stone.tech/customer-auth-method: not-applicable
  links:
    - url: https://github.com/pagarme/backstage/actions/workflows/deploy_prd.yaml
      title: CD Pipeline
    - url: https://app.datadoghq.com/dashboard/fpr-ncq-gnm/backstage
      title: Monitoring
    - url: https://app.datadoghq.com/monitors/manage?q=service%3A%22backstage%22
      title: Incident Manager
spec:
  type: website
  lifecycle: production
  owner: stone-payments/platform-squad-writer
  system: platform
  dependsOn:
    - resource:backstage-database
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-portal
  namespace: stone-payments
  title: Backstage Portal
  description: The StoneCo developer portal
  annotations:
    stone.tech/cloud-accounts: aws/pagarme-tools
    legacy.stone.tech/prod-date: "2023-03-01"
    legacy.stone.tech/owner-email: dmorales@stone.com.br
  labels:
    stone.tech/endpoint-type: private
    legacy.stone.tech/internal-user-auth-base: sso
    legacy.stone.tech/access-request-type: github
    legacy.stone.tech/handle-lgpd: "false"
    legacy.stone.tech/customer-auth-method: not-applicable
  links:
    - url: https://github.com/pagarme/backstage/actions/workflows/deploy_prd.yaml
      title: CD Pipeline
    - url: https://app.datadoghq.com/dashboard/fpr-ncq-gnm/backstage
      title: Monitoring
    - url: https://app.datadoghq.com/monitors/manage?q=service%3A%22backstage%22
      title: Incident Manager
spec:
  type: second-error
  lifecycle: production
  owner: stone-payments/platform-squad-writer
  system: platform
  dependsOn:
    - resource:backstage-database