apiVersion: backstage.com/v1alpha2
kind: Pod
metadata:
  name: nginx
  annotations:
    example: backstage.io
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80
  - name: nginx2
    image: nginx:1.14.2
    ports:
    - containerPort: 80